const subjectMap = {
  "AAS": "Asian American Studies",
  "ABE": "Agricultural and Biological Engineering",
  "ACCY": "Accountancy",
  "ACE": "Agricultural and Consumer Economics",
  "ACES": "Agricultural, Consumer and Environmental Sciences",
  "ADV": "Advertising",
  "AE": "Aerospace Engineering",
  "AFRO": "African American Studies",
  "AFST": "African Studies",
  "AGCM": "Agricultural Communications",
  "AGED": "Agricultural Education",
  "AHS": "Applied Health Sciences",
  "AIS": "American Indian Studies",
  "ALEC": "Agricultural Leadership, Education, and Communications",
  "ANSC": "Animal Sciences",
  "ANTH": "Anthropology",
  "ARAB": "Arabic",
  "ARCH": "Architecture",
  "ART": "Art",
  "ARTD": "Art--Design",
  "ARTE": "Art--Education",
  "ARTF": "Art--Foundation",
  "ARTH": "Art--History",
  "ARTS": "Art--Studio",
  "ASST": "Asian Studies",
  "ASTR": "Astronomy",
  "ATMS": "Atmospheric Sciences",
  "BADM": "Business Administration",
  "BCOG": "Brain and Cognitive Science",
  "BDI": "Business Data Innov & Analytics",
  "BIOE": "Bioengineering",
  "BIOL": "Biology",
  "BIOP": "Biophysics",
  "BSE": "Business Simulation & Experiential",
  "BUS": "Business",
  "CB": "Comparative Biosciences",
  "CBM": "Carle Illinois College of Medicine",
  "CEE": "Civil and Environmental Engineering",
  "CHBE": "Chemical and Biomolecular Engineering",
  "CHEM": "Chemistry",
  "CHIN": "Chinese",
  "CHLH": "Community Health",
  "CHP": "Campus Honors Program",
  "CI": "Curriculum and Instruction",
  "CIC": "Committee on Inst Cooperation",
  "CLCV": "Classical Civilization",
  "CLE": "Campus Legal Education",
  "CMN": "Communication",
  "CPSC": "Crop Sciences",
  "CS": "Computer Science",
  "CW": "Creative Writing",
  "CZCH": "Czech",
  "DANC": "Dance",
  "EALC": "East Asian Languages and Cultures",
  "ECE": "Electrical and Computer Engineering",
  "ECON": "Economics",
  "EDUC": "Education",
  "EIL": "English as an International Language",
  "ENG": "Engineering",
  "ENGL": "English",
  "ENSU": "Environmental Sustainability",
  "ENT": "Entomology",
  "EPOL": "Education Policy, Organization and Leadership",
  "EPS": "Educational Policy Studies",
  "EPSY": "Educational Psychology",
  "ERAM": "Erasmus",
  "ESE": "Earth, Society, and Environmental Sustainability",
  "ESL": "English as a Second Language",
  "EURO": "European Union Studies",
  "FAA": "Fine and Applied Arts",
  "FIN": "Finance",
  "FLA": "Foreign Language Applications",
  "FSHN": "Food Science and Human Nutrition",
  "GC": "Graduate College",
  "GEOG": "Geography and Geographic Information Science",
  "GEOL": "Geology",
  "GER": "German",
  "GLBL": "Global Studies",
  "GMC": "Gies Management Cohort",
  "GRK": "Greek",
  "GS": "General Studies",
  "GWS": "Gender and Women's Studies",
  "HDFS": "Human Development and Family Studies",
  "HEBR": "Hebrew",
  "HIST": "History",
  "HNDI": "Hindi",
  "HORT": "Horticulture",
  "HRD": "Human Resource Development",
  "IB": "Integrative Biology",
  "IE": "Industrial Engineering",
  "INFO": "Informatics",
  "IS": "Information Sciences",
  "ITAL": "Italian",
  "JAPN": "Japanese",
  "JOUR": "Journalism",
  "KIN": "Kinesiology",
  "KOR": "Korean",
  "LA": "Landscape Architecture",
  "LAS": "Liberal Arts and Sciences",
  "LAST": "Latin American and Caribbean Studies",
  "LAT": "Latin",
  "LAW": "Law",
  "LEAD": "Leadership Studies",
  "LER": "Labor and Employment Relations",
  "LING": "Linguistics",
  "LLS": "Latina/Latino Studies",
  "MACS": "Media and Cinema Studies",
  "MATH": "Mathematics",
  "MBA": "Business Administration",
  "MCB": "Molecular and Cellular Biology",
  "MDIA": "Media",
  "ME": "Mechanical Engineering",
  "MICR": "Microbiology",
  "MILS": "Military Science",
  "MSE": "Materials Science and Engineering",
  "MUS": "Music",
  "MUSE": "Museum Studies",
  "NPRE": "Nuclear, Plasma, and Radiological Engineering",
  "NRES": "Natural Resources and Environmental Sciences",
  "NS": "Naval Science",
  "NUTR": "Nutritional Sciences",
  "PATH": "Pathobiology",
  "PE": "Physical Education",
  "PHIL": "Philosophy",
  "PHYS": "Physics",
  "PLPA": "Plant Pathology",
  "POL": "Polish",
  "PORT": "Portuguese",
  "PS": "Political Science",
  "PSM": "Professional Science Master's",
  "PSYC": "Psychology",
  "REES": "Russian, East European and Eurasian Studies",
  "RHET": "Rhetoric and Composition",
  "RST": "Recreation, Sport and Tourism",
  "RUSS": "Russian",
  "SBC": "Strategic Brand Communication",
  "SCAN": "Scandinavian",
  "SE": "Systems Engineering",
  "SHS": "Speech and Hearing Science",
  "SLAV": "Slavic",
  "SOC": "Sociology",
  "SOCW": "Social Work",
  "SPAN": "Spanish",
  "SPED": "Special Education",
  "STAT": "Statistics",
  "TE": "Technology Entrepreneurship",
  "THEA": "Theatre",
  "TRST": "Translation Studies",
  "TSM": "Technical Systems Management",
  "UKR": "Ukrainian",
  "UP": "Urban and Regional Planning",
  "VCM": "Veterinary Clinical Medicine",
  "VM": "Veterinary Medicine",
  "YDSH": "Yiddish",
  "ARTJ": "Art--Japanese",
  "ASRM": "Actuarial Science and Risk Management",
  "AVI": "Aviation",
  "BCS": "Bosnian-Croatian-Serbian",
  "BIOC": "Biochemistry",
  "BTW": "Business and Technical Writing",
  "CINE": "Cinema Studies",
  "CWL": "Comparative and World Literature",
  "DTX": "Human-Centered Design & Design Thinking",
  "ENVS": "Environmental Studies",
  "EOL": "Educational Organization and Leadership",
  "ETMA": "Engineering Technology & Management for Agricultural Systems",
  "FR": "French",
  "GCL": "Grand Challenge Learning",
  "GE": "General Engineering",
  "GGIS": "Geography and Geographic Information Science",
  "GRKM": "Modern Greek",
  "GSD": "Game Studies and Design",
  "HK": "Health and Kinesiology",
  "HRE": "Human Resource Education",
  "IHLT": "Interdisciplinary Health Sciences",
  "JS": "Jewish Studies",
  "LIS": "Library and Information Science",
  "MS": "Medical Scholars",
  "MUSC": "Music",
  "NE": "Nuclear Engineering",
  "REHB": "Rehabilitation Counseling",
  "REL": "Religion",
  "RLST": "Religious Studies",
  "RSOC": "Rural Sociology",
  "SAME": "South Asian and Middle Eastern Studies",
  "SCR": "Serbo-Croatian",
  "SLCL": "School of Literatures, Cultures and Linguistics",
  "SWAH": "Swahili",
  "TAM": "Theoretical and Applied Mechanics",
  "VB": "Veterinary Biosciences"
};

export default subjectMap;
